// Generated by Unloop
// Weather Station

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_record_clicked(|| {
        println!("record clicked");
    });
    
    app.on_history_clicked(|| {
        println!("history clicked");
    });
    

    
    app.run()
}
