// Generated Data Model

export struct AppData {
    temperature: float,
    humidity: float,
    pressure: float,
    wind-speed: float,
    wind-direction: string,
    temp-trend: string,
    humidity-trend: string,
    pressure-trend: string,
    sensor-status: string,
    logger-status: string,
    weather-history: string,
    temp-unit: string,
    wind-unit: string,
    pressure-unit: string,
    auto-record: bool,
    record-interval: float,
    version: string,
}
